In [2]:
import numpy  as np
tmp_array = np.arange(1000000)
tmp_list = list(range(1000000))

# testing the numpy performance
%time for _ in range(10): tmp_array = tmp_array *2
%time for _ in range(10): tmp_list = [x*2 for x in tmp_list]

CPU times: user 7.75 ms, sys: 10 µs, total: 7.76 ms
Wall time: 7.76 ms
CPU times: user 498 ms, sys: 110 ms, total: 608 ms
Wall time: 610 ms


In [9]:
import numpy as np
# generate two row three cols array
data = np.random.randn(2,3)

# # 对应位置乘10
# data * 10

# # 对应位置相加
# data + data

# # 数组的结构 dimension
# data.shape
# # 数组中的数据类型
# data.dtype

dtype('float64')

In [15]:
import numpy as np

data1 = [1,2,3,4,5.5]
arr1 = np.array(data1)

data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

arr3 = np.array([1, 2, 3], dtype=np.float64)


# 二维数组，3行六列，都是0
np.zeros((3,6))

# 三维数组，3层，2行4列
np.empty((3,2,4))

array([1., 2., 3.])

In [16]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr.dtype
# array数据的类型转换
float_arr = arr.astype(np.float64)

dtype('int64')

In [20]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[2,2,3],[4,5,6]])

# 对应位置想乘
arr*arr

# 对应位置相减
arr - arr

# 对应位置相除
1 / arr

# 对应位置相比较
arr1 > arr

array([[ True, False, False],
       [False, False, False]])

In [25]:
import numpy as np
arr = np.arange(10)

# 第六个元素
arr[5]
# 第6个元素开始，后面三个，不包括第九个
arr[5:8]

# 基于数组做的slice的子数组，所有操作会反映到原数据上
arr_slice = arr[5:8]
arr_slice[1] = 12345
# 给所有元素赋值
arr_slice[:] = 4

array([4, 4, 4])

In [36]:
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 二维数组的第三行
arr2d[2]
# 二维数组的第2行.2号位
arr2d[1][1]

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# 三维数组的第一层
arr3d[0]

old_val = arr3d[0].copy()

# 第一层所数值 变为 42
arr3d[0] = 42

arr3d[0] = old_val
# 第二层，第1行元素
arr3d[1,0]


array([7, 8, 9])

In [37]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# 从0号位开始，往后取两行
arr2d[:2]
# 从0号位开始，往后取两行； 从第二列开始，取完
arr2d[:2, 1:]
# 第二行； 从0开始，取两列
arr2d[1, :2]

array([4, 5])

In [40]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

names == 'Bob'
# 根据TF 选行数
data[names == 'Bob']
# 根据TF 选行数； 从第三列开始，全选
data[names == 'Bob', 2:]
# 非
data[~(names == 'Bob')]
# 将小于0的数据 变为0
data[data < 0] = 0

array([ True, False, False,  True, False, False, False])

In [45]:
import numpy as np
arr = np.empty((8, 4))
# 赋值
for i in range(8):
    arr[i] = i

# 取对应的行数
arr[[4, 3, 0, 6]]
# 反向取行数，从-1 开始
arr[[-3, -5, -7]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [47]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
# 行列反转，3rows 5cols -》 5rows 3cols
arr.T

# 矩阵点积，第一个数组的列数，必须和第二个数组的行数一样
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])